# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/menus

main:
  - label: "O nás"
    link: "/page/o-nas"
    description: "Časová osa – založení, nový jednatel, noví společníci."

  - label: "Služby"
    submenu:
      - label: "Rehabilitace"
        link: "/page/rehabilitace"
        submenu:
          - label: "Fyzioterapie"
            link: "/page/fyzioterapie"
          - label: "Myoskeletální medicína"
            link: "/page/myoskeletalni-medicina"
          - label: "Fyzikální terapie"
            link: "/page/fyzikalni-terapie"

      - label: "Rehabilitační ambulance"
        link: "/page/rehabilitacni-ambulance"
      - label: "Ortopedická ambulance"
        link: "/page/ortopedicka-ambulance"
      - label: "Skupinová cvičení"
        link: "/page/skupinova-cviceni"
      - label: "Masáže"
        link: "/page/masaze"
      - label: "Pronájem mokré zóny"
        link: "/page/pronajem-mokre-zony"
      - label: "Akupunktura"
        link: "/page/akupunktura"

  - label: "Náš tým"
    link: "/page/nas-tym"
    description: "Foto, jméno, příjmení, pracovní zařazení."

  - label: "Ceník"
    link: "/page/cenik"
    description: "Stručná přehledná tabulka – lékař, rehabilitace, pronájem, rehabilitační pomůcky."

  - label: "Recenze"
    link: "/page/recenze"
    description: "Možnost napsat přímo názor do formuláře. Formulář bude odesílán na web a viditelný v admin rozhraní."
    note: "Sekce s recenzemi na homepage bude statická."

  - label: "Smluvní pojišťovny"
    link: "/page/pojistovny"
    description: "Loga pojišťoven, se kterými máme uzavřen smluvní vztah."

  - label: "Kontakt"
    link: "/page/kontakt"
    description: "Adresa, mapa, IČO, email, telefon, provozní doba."

foo: bar

social:
  - label: 'Facebook'
    title: Facebook
    link: 'https://facebook.com/'
    class: fab fa-facebook
    submenu: null
    uri: ''
     
  - label: 'Instagram'
    title: Instagram
    link: 'https://instagram.com/'
    class: fab fa-linkedin
    submenu: null
    uri: ''
