
# 'Sections' Content Type
# Sections are bigger blocks added on one or more pages / section groups mostly under the main content.
# They should contain information about a particular page eg, listings of content, galleries...
# Unlike blocks, sections are related to pages or content type templates (eg. recors, entries...)
# so each section can be added to more places with no need to specifying in template itself.
#
# Since we cannot define own content types within theme, we must specify own content tyoe explicitely in contenttypes.yml.
sections:
    name: Sections
    singular_name: Section
    fields:
        title:
            type: text
            class: large
            group: "Block"
        slug:
            type: slug
            uses: [ title ]
        content:
            type: redactor
            height: 150px
            fixture_format: '{paragraph}'
        image:
            type: image
            attrib: title
            extensions: [ gif, jpg, png ]
        gallery:
            imagelist:
            type: imagelist
            extensions: [ gif, jpg, png ]
            upload: gallery
        contentlink:
            group: contentBlock
            type: text
            label: Content Link
            placeholder: 'contenttype/slug or http://example.org/'
            postfix: "Use this to add a link for this Block. This could either be an 'internal' link like <tt>page/about</tt>, if you use a contenttype/slug combination."
            fixture_format: '{url}'
        contentlimit:
            group: contentBlock
            type: number
        contentselect:
            group: contentBlock
            type: select
            values: (blocks,pages,entries,products)/{contenttype} | {title} № {id} ({status})
            autocomplete: true
            multiple: true
        contenttemplate:
            label: Content Template
            group: contentBlock
            type: templateselect
            filter: /^twig\/contentblock\/.*?.twig$/
        links:
            type: collection 
            group: Links
            postfix: "Additional links for the section"
            fields:
                links:
                    type: set
                    fields:
                        title:
                            type: text
                        contentlink:
                            type: text
                            placeholder: 'contenttype/slug'
                            postfix: "Slug"
                            fixture_format: '{url}'
    relations:
        pages:
            multiple: true
            label: "Related pages"
            # format: "{{item.title}} (№ {{item.id}})"
            postfix: "By selecting a Content Block, you're creating a bi-directional relationship to that Content Block."
    taxonomy: [ sectiongroups ]
    show_on_dashboard: true
    viewless: true
    default_status: published
    searchable: false
    icon_many: "fa:puzzle-piece"
    icon_one: "fa:puzzle-piece"
